version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    container_name: minio_s3
    command: server /data --console-address ":9002"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
