import type { Hotel } from "./types"

export const mockHotels: Hotel[] = [
  {
    id: "1",
    name: "Hôtel Colbert Antananarivo",
    description: "Hôtel de luxe au cœur de la capitale malgache avec vue panoramique sur la ville.",
    address: "Rue Prince Ratsimamanga, Antananarivo",
    city: "Antananarivo",
    region: "Analamanga",
    coordinates: { lat: -18.8792, lng: 47.5079 },
    priceRange: { min: 80000, max: 150000 },
    rating: 4.5,
    amenities: ["WiFi", "Piscine", "Restaurant", "Spa", "Parking", "Climatisation"],
    images: ["/luxury-hotel-antananarivo.png"],
    category: "luxury",
    badges: ["Recommandé", "Vue panoramique"],
    availability: true,
    hotelierEmail: "hotelier@example.mg",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Andasibe Forest Lodge",
    description: "Lodge écologique au cœur de la forêt primaire, idéal pour observer les lémuriens.",
    address: "Parc National Andasibe-Mantadia",
    city: "Andasibe",
    region: "Alaotra-Mangoro",
    coordinates: { lat: -18.9465, lng: 48.4166 },
    priceRange: { min: 45000, max: 85000 },
    rating: 4.2,
    amenities: ["WiFi", "Restaurant", "Guide nature", "Parking"],
    images: ["/placeholder-y1l3j.png"],
    category: "eco",
    badges: ["Écologique", "Observation faune"],
    availability: true,
    hotelierEmail: "hotelier@example.mg",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Nosy Be Beach Resort",
    description: "Resort familial sur la plage avec activités nautiques et club enfants.",
    address: "Plage d'Ambatoloaka, Nosy Be",
    city: "Nosy Be",
    region: "Diana",
    coordinates: { lat: -13.3203, lng: 48.2619 },
    priceRange: { min: 60000, max: 120000 },
    rating: 4.3,
    amenities: ["WiFi", "Piscine", "Restaurant", "Plage privée", "Club enfants", "Sports nautiques"],
    images: ["/nosy-be-resort.png"],
    category: "family",
    badges: ["Plage privée", "Famille"],
    availability: true,
    hotelierEmail: "hotelier@example.mg",
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Business Hotel Toamasina",
    description: "Hôtel moderne pour voyageurs d'affaires avec centre de conférences.",
    address: "Boulevard Joffre, Toamasina",
    city: "Toamasina",
    region: "Atsinanana",
    coordinates: { lat: -18.1492, lng: 49.4024 },
    priceRange: { min: 55000, max: 95000 },
    rating: 4.0,
    amenities: ["WiFi", "Centre affaires", "Restaurant", "Salle de conférence", "Parking"],
    images: ["/business-hotel-toamasina.png"],
    category: "business",
    badges: ["Centre affaires", "Conférences"],
    availability: true,
    hotelierEmail: "hotelier@example.mg",
    createdAt: new Date(),
  },
]
